
CREATE TABLE DEPARTMENT (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL
)ENGINE=INNODB;

CREATE TABLE ROLE (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL UNIQUE
)ENGINE=INNODB;

CREATE TABLE USER (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USERNAME` VARCHAR(255) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(100) NOT NULL ,
  `EMAIL` VARCHAR(1000) NOT NULL UNIQUE,
  `FIRST_NAME` VARCHAR(120) NOT NULL ,
  `LAST_NAME` VARCHAR(120) NULL ,
  `ROLE_ID` BIGINT NOT NULL,
  `REGISTRATION_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (`ROLE_ID`)
  REFERENCES  `ROLE` (`ID`)
)ENGINE=INNODB;

CREATE TABLE DOCTOR (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL,
  `DEPARTMENT_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `PHONE` BIGINT NOT NULL,
  `ADDRESS` VARCHAR(1000) NULL ,
  `DESIGNATION` VARCHAR(1000) NULL ,
  `SPECIALITY` VARCHAR(1000) NULL ,
  `BIO` VARCHAR(3000) NOT NULL ,
  `VISIT_AMOUNT` DECIMAL NOT NULL,

  --  CONSTRAINT `FK_DEPARTMENT_ID`
  FOREIGN KEY (`DEPARTMENT_ID`)
  REFERENCES `DEPARTMENT` (`ID`)
  --    ON DELETE RESTRICT
  --    ON UPDATE CASCADE
  ,
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USER` (`ID`)
)ENGINE=INNODB;

CREATE TABLE PATIENT (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `AGE` INT NULL ,
  `WEIGHT` INT NULL ,
  `TYPE` INT NOT NULL , -- 1 indoore, 2 outdoor
  `ADDRESS` VARCHAR(1000) NULL ,
  `COMMENT` VARCHAR(1000) NULL , -- problem
  `PHONE` BIGINT NULL
  ,
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USER` (`ID`)
)ENGINE=INNODB;

CREATE TABLE APPOINTMENT (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NOT NULL,
  `DESCRIPTION` VARCHAR(1000) NULL,
  `VISITED` INT NULL  DEFAULT 0,
  `DATE` DATE NOT NULL ,
  `TIME` TIME NOT NULL ,

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`)
)ENGINE=INNODB;

CREATE TABLE PRESSCRIPTION (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NOT NULL,
  `REF_DOCTOR_ID` BIGINT NULL,
  `APPOINTMENT_ID` BIGINT NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `SUMMERY` VARCHAR(1000) NULL,
  `DIAGNOSIS` VARCHAR(1000) NULL,
  `ADVICE` VARCHAR(1000) NULL,
  `TEST` VARCHAR(1000) NULL,
  `MEDICINE` VARCHAR(5000) NULL,
  `COMMENT` VARCHAR(1000) NULL,
  `DATE` DATE NOT NULL ,
  `TIME` TIME NOT NULL ,

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`REF_DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`APPOINTMENT_ID`)
  REFERENCES APPOINTMENT (`ID`)
)ENGINE=INNODB;


CREATE TABLE REPORT (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `SUMMERY` VARCHAR(1000) NULL,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NOT NULL,
  `PRESSCRIPTION_ID` BIGINT NOT NULL,
  `DIAGNOSIS` VARCHAR(1000) NULL,
  `FINDINGS` VARCHAR(1000) NULL,
  `MEDICINE` VARCHAR(5000) NULL,
  `COMMENT` VARCHAR(1000) NULL,
  `DATE` DATE NOT NULL ,
  `TIME` TIME NOT NULL ,

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`PRESSCRIPTION_ID`)
  REFERENCES `PRESSCRIPTION` (`ID`)
)ENGINE=INNODB;


CREATE TABLE DOCTOR_SCHEDULE (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `SCHEDULE_DETAILS` VARCHAR(2000) NULL,
  `SUMMERY` VARCHAR(1000) NULL,
  `COMMENT` VARCHAR(1000) NULL,
  `DOCTOR_ID` BIGINT NOT NULL,
  `FROM_TIME` TIME NULL ,
  `TO_TIME` TIME NULL ,
  `DAYS` VARCHAR(255)  NULL ,

  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`)
)ENGINE=INNODB;

CREATE TABLE ADMITED_PATIENTS(
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NULL,
  `PRESSCRIPTION_ID` BIGINT NULL,
  `REPORT_ID` BIGINT NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `SUMMERY` VARCHAR(1000) NULL,
  `MEDICINE` VARCHAR(5000) NULL,
  `COMMENT` VARCHAR(1000) NULL,
  `FROM_DATE` DATE NULL ,
  `TO_DATE` TIME NULL ,

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`PRESSCRIPTION_ID`)
  REFERENCES `PRESSCRIPTION` (`ID`),
  FOREIGN KEY (`REPORT_ID`)
  REFERENCES `REPORT` (`ID`)
)ENGINE=INNODB;


CREATE TABLE PATIENTS_BILL(
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `NAME` VARCHAR(255) NULL,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NULL,
  `PRESSCRIPTION_ID` BIGINT NULL,
  `REPORT_ID` BIGINT NULL,
  `PAID_AMOUNT` DECIMAL NULL,
  `PAYABLE_AMOUNT` DECIMAL NOT NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `PAYMENT_STATUS` INT NULL DEFAULT 0, -- 1 means Paid

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`PRESSCRIPTION_ID`)
  REFERENCES `PRESSCRIPTION` (`ID`),
  FOREIGN KEY (`REPORT_ID`)
  REFERENCES `REPORT` (`ID`)
)ENGINE=INNODB;



CREATE TABLE SURGERY(
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `NAME` VARCHAR(255) NULL,
  `PATIENT_ID` BIGINT NOT NULL,
  `DOCTOR_ID` BIGINT NOT NULL,
  `PRESSCRIPTION_ID` BIGINT NULL,
  `REPORT_ID` BIGINT NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `STATUS` VARCHAR(255) NULL, -- successful, unsuccessful
  `SUMMERY` VARCHAR(1000) NULL,
  `MEDICINE` VARCHAR(5000) NULL,
  `COMMENT` VARCHAR(1000) NULL,
  `DATE` DATE NULL ,

  FOREIGN KEY (`PATIENT_ID`)
  REFERENCES `PATIENT` (`ID`),
  FOREIGN KEY (`DOCTOR_ID`)
  REFERENCES `DOCTOR` (`ID`),
  FOREIGN KEY (`PRESSCRIPTION_ID`)
  REFERENCES `PRESSCRIPTION` (`ID`),
  FOREIGN KEY (`REPORT_ID`)
  REFERENCES `REPORT` (`ID`)
)ENGINE=INNODB;


CREATE TABLE HOSPITAL_INFO(
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `NAME` VARCHAR(255) NULL,
  `TITLE` VARCHAR(255) NULL,
  `THEAM` VARCHAR(500) NULL,
  `ADDRESS` VARCHAR(500) NULL,
  `CONTRACT` VARCHAR(500) NULL,
  `EMMERGENCY` VARCHAR(500) NULL,
  `HELPLINE` VARCHAR(500) NULL,
  `DESCRIPTION` VARCHAR(2000) NULL,
  `ABOUT_US` VARCHAR(2000) NULL,
  `EMAIL` VARCHAR(1000) NULL,
  `DETAIL1` VARCHAR(2000) NULL,
  `DETAIL2` VARCHAR(2000) NULL,
  `DETAIL3` VARCHAR(2000) NULL,
  `DETAIL4` VARCHAR(2000) NULL,
  `DETAIL5` VARCHAR(2000) NULL,
  `DATE` DATE NULL
)ENGINE=INNODB;


